### ISSUE TITLE
Build CaseLog

### ISSUE THREAD

**Issue by cbothner** [galahq/gala#199]
- [x] Accept comments that aren’t tied to a specific section of the text (#184)
- [x] Automatically add instructors to a special instructors-only discussion community (#200)
- [x] Provide special instructions in the NoSelectedCommentThread pane; special icon too (#201)
- [ ] Send automatic prompt emails when it seems like an instructor has recently finished using a case (#202)
