### ISSUE TITLE
Enhance the case overview so it functions as most of a teaching guide

### ISSUE THREAD

**Issue by cbothner** [galahq/gala#58]
Visible to all users of the case as metadata
- [ ] **Keywords**: “what kinds of classes is this useful for?”
- [x] **Learning objectives**: clauses/bullet points
- [ ] **Suggested audience**: what background knowledge + resources for those missing that

Visible only to professors:
- [ ] **Exercise instructions and answers**
- [ ] **Suggested classroom timeline**: reference lengths for smallest indivisible chunks of activity, grouped into sets between which it's most smooth to take a break if needed.
